### ISSUE TITLE
Strefa z wyznaczonym obozem

### ISSUE THREAD

**Issue by Przemro** [Przemro/Wsparcie_dla_MM.VR#1]
Dobrym dodatkiem do misji może być dodanie strefy "obozowej" w której gracz wyznacza gdzie ma być postawiony obóz a nie zostawia to losowości DAC`a.

**Comment by Xawery94** [comment]
Nie będzie większego problemu z dodaniem tego, także muszę przejrzeć wszystkie moduły ponieważ ACE dodał dodatkowe opcje w modułach, które używamy na misjach i trzeba niektóre opcje powyłączać, jak np. dodatkowe zatyczki dla klas specjalnych typu: RKM, AA, AT.

**Comment by Xawery94** [comment]
Zrobione, zamykam.
